### ISSUE TITLE
Make sure the landmark file produce the Golden model (for both speakers av and cs)

### ISSUE THREAD

**Issue by winkijeg** [winkijeg/SPEECHart#14]
Check if av_MRI.xml produce the same model in Golden file av_model.xml. Check also for speaker cs

**Comment by winkijeg** [comment]
Models provided as Golden standard can be reproduced. Diff of golden models and actual generated models revealed minimal differences - one digit in twelfth decimal place.

script script_demonstrate_SpeakerModel.m is tested successfully.

**Comment by susfuchs** [comment]
Tested av and everything seems to work for av 👍 , but still have an issue saving the speakerEditor data with new data.

**Comment by winkijeg** [comment]
yes, no surprise, after re-activating the grid-sampling in the Save-button callback there are quit a lot of assumtions to be meet for successful savoing. Will open a new ticket, because we need to separate between temporary landmarks/contours and final (at least) contours damples on grit for model build.
